# Generated by Django 3.0.7 on 2020-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=6)),
                ('professori', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=20)),
                ('spiegazione', models.IntegerField(default=0)),
                ('preparazione', models.IntegerField(default=0)),
                ('valutazioni', models.IntegerField(default=0)),
                ('metodo', models.IntegerField(default=0)),
                ('rapporto', models.IntegerField(default=0)),
                ('n_voti', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Votazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiegazione', models.IntegerField()),
                ('preparazione', models.IntegerField()),
                ('valutazioni', models.IntegerField()),
                ('metodo', models.IntegerField()),
                ('rapporto', models.IntegerField()),
            ],
        ),
    ]
