# Generated by Django 3.0.7 on 2020-06-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
