# Generated by Django 3.0.7 on 2020-09-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studente',
            old_name='has_voted',
            new_name='ha_votato',
        ),
    ]
