# Generated by Django 3.0.7 on 2020-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=20)),
            ],
        ),
    ]
