# Generated by Django 3.0.7 on 2020-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_professore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=50)),
                ('spiegazione', models.IntegerField()),
                ('preparazione', models.IntegerField()),
                ('valutazioni', models.IntegerField()),
                ('metodo', models.IntegerField()),
                ('rapporto', models.IntegerField()),
            ],
        ),
    ]
